spring:
  application:
    name: spring-boot
  datasource:
    driver-class-name: org.sqlite.JDBC
    #    remote
    #    url: /hy-tmp/webapp

    #    local
    url: D:\\code\\SoftWareProject\\backend\\webapp

server:
  port: 9090
#remote
#local-img:
#  save-path: /hy-tmp/usrPic/
#  request-path: /usrPic/**
#  r-path: /usrPic/

#local
local-img:
  save-path: D:\\code\\SoftWareProject\\usrPic\\
  request-path: /usrPic/**
  r-path: /usrPic/
