spring:
  application:
    name: spring-boot
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: D:\\code\\SoftWareProject\\backend\\webapp

server:
  port: 9090

logging:
  level:
    root=DEBUG:
local-img:
  save-path: D:\\code\\SoftWareProject\\usrPic\\
  request-path: /usrPic/**
  r-path: /usrPic/
